language: node_js
node_js:
- node
install:
- npm install
script:
- npm run build
deploy:
  - provider: releases
    api_key:
      secure: iwFwhCvn2wPXifWbKumeumRm5rZrV1jafqRFdWqovx74QaDc1naaoHD25a8RfowlEbUjUk+RA8jTemHM5KPiN1jd6fQyjHt6fCC+iZqFUKNtktderYLO4yuSYNV18yP7P/zRiOJ+sfg85Sd7XWGgp40jqyK6o6LI0/ELfLO8QxErFu9zX0rII3yhncEqQW1xSS+Zl1cWtPOK5TL6X2PHFunsl9tJ9lpQhSQ8NBMObYlAaubtpWXUV6D8mRUcjGyeUSKSXPdbtRtYUVe8sL93c9SEWi+8hetyfjmh+k/33iImF1WeaoA3FSaN5BezqcBuuSumTiOGu1NwWUs93GwEEUR4EWXNSLOAPuwcvBS+l4CbHzR/HVxONHixgXeYg+YkaJBVZBiiUMQ3qoWM7wiBJfCz+4DmN/jsl2Mlfe2TppQbPr6752GvRWNiEtceSSDD31z2BhBgQ5f3m/jTyQ7j2sTcAmtMzzzIpY9D/twwIZ6KlegJNOgTjKCjfe9t0wOszzr5lfPhoId4l3IIE4d42vXTAFtoyxi+DmZZvwCVNcjBM10U5Y7+S5vt9X5AsbImxlZpN+KnGgsGp49wWDGWwousrIsAI0vomW9+6320oJqBtPjLNLnh4bMI5Pxhp2PRXVwqM/nmw05J5GD2MoXyI7d5LgBpDdDZ5pFKMyi/j/0=
    file: bundle/youngblood.min.js
    on:
      tags: true
      branch: master
      repo: zsombro/youngblood
  - provider: npm
    email: berki.zsombor@gmail.com
    skip_cleanup: true
    api_key:
      secure: MuF2XS+vyvw1eUqIJE9wc8JEr7R3R8qO2+FoiXUD6q/cgfN1yYbLWWfp7IAyHx3SQrUULuT3eDtvw8MXENxIIj0ZS+Ir9iX408IZZGle4gbUF9ci2I8TVbsmDOkid5RgJ8YZcqTPntONmuKn+ZET0DYoMi6rnjpb+kIOsuvU4AeIOnSEscvceOafXmCjtSPo6VgcBi3hDda1LxRAEOiq2fk9rZAHnGg6ViM8DRpofNE3F9on3vheDUCQK5Y0cYXOp7vFTGPWaem9h/8Mb7H/N1ey+dtuOhQcsyStoRGr5fToij/iAQcBAqJqK5VyrhCGoaxva7Af1xCvMUXQSrXsrTmxErYj4H7d/R9IEIFgVW4eoKiqB/R6I3aoDVIi7eHwxxdNDdpXlJQN7oTGxV97fzZ4SSUI00evzNkh/7PGAuHNLejubQoupEpEQf5OrNCc/bOM7/UoxegN+IoTk/RxSdByyvdiNpgyozH9JJzl/OQ+goFkHjHCtgvUhJ6xSIZBluXqNxd4X7+ze6NI/TvxiZ8f+09q/v6D727NWlzM=
    on:
      tags: true
      branch: master
      repo: zsombro/youngblood